// Code generated by MockGen. DO NOT EDIT.
// Source: ../interfaces/index_base_service.go
//
// Generated by this command:
//
//	mockgen -source ../interfaces/index_base_service.go -destination ../interfaces/mock/mock_index_base_service.go
//

// Package mock_interfaces is a generated GoMock package.
package mock_interfaces

import (
	context "context"
	interfaces "flow-stream-data-pipeline/pipeline-worker/interfaces"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockIndexBaseService is a mock of IndexBaseService interface.
type MockIndexBaseService struct {
	ctrl     *gomock.Controller
	recorder *MockIndexBaseServiceMockRecorder
	isgomock struct{}
}

// MockIndexBaseServiceMockRecorder is the mock recorder for MockIndexBaseService.
type MockIndexBaseServiceMockRecorder struct {
	mock *MockIndexBaseService
}

// NewMockIndexBaseService creates a new mock instance.
func NewMockIndexBaseService(ctrl *gomock.Controller) *MockIndexBaseService {
	mock := &MockIndexBaseService{ctrl: ctrl}
	mock.recorder = &MockIndexBaseServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIndexBaseService) EXPECT() *MockIndexBaseServiceMockRecorder {
	return m.recorder
}

// GetIndexBaseByBaseType mocks base method.
func (m *MockIndexBaseService) GetIndexBaseByBaseType(ctx context.Context, baseType string) (*interfaces.IndexBaseInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIndexBaseByBaseType", ctx, baseType)
	ret0, _ := ret[0].(*interfaces.IndexBaseInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetIndexBaseByBaseType indicates an expected call of GetIndexBaseByBaseType.
func (mr *MockIndexBaseServiceMockRecorder) GetIndexBaseByBaseType(ctx, baseType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIndexBaseByBaseType", reflect.TypeOf((*MockIndexBaseService)(nil).GetIndexBaseByBaseType), ctx, baseType)
}
