// Code generated by MockGen. DO NOT EDIT.
// Source: ../interfaces/data_dict_access.go
//
// Generated by this command:
//
//	mockgen -source ../interfaces/data_dict_access.go -destination ../interfaces/mock/mock_data_dict_access.go
//

// Package mock_interfaces is a generated GoMock package.
package mock_interfaces

import (
	context "context"
	reflect "reflect"
	interfaces "uniquery/interfaces"

	gomock "go.uber.org/mock/gomock"
)

// MockDataDictAccess is a mock of DataDictAccess interface.
type MockDataDictAccess struct {
	ctrl     *gomock.Controller
	recorder *MockDataDictAccessMockRecorder
	isgomock struct{}
}

// MockDataDictAccessMockRecorder is the mock recorder for MockDataDictAccess.
type MockDataDictAccessMockRecorder struct {
	mock *MockDataDictAccess
}

// NewMockDataDictAccess creates a new mock instance.
func NewMockDataDictAccess(ctrl *gomock.Controller) *MockDataDictAccess {
	mock := &MockDataDictAccess{ctrl: ctrl}
	mock.recorder = &MockDataDictAccessMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDataDictAccess) EXPECT() *MockDataDictAccessMockRecorder {
	return m.recorder
}

// GetDictInfo mocks base method.
func (m *MockDataDictAccess) GetDictInfo(ctx context.Context, dictName string) (interfaces.DataDict, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDictInfo", ctx, dictName)
	ret0, _ := ret[0].(interfaces.DataDict)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDictInfo indicates an expected call of GetDictInfo.
func (mr *MockDataDictAccessMockRecorder) GetDictInfo(ctx, dictName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDictInfo", reflect.TypeOf((*MockDataDictAccess)(nil).GetDictInfo), ctx, dictName)
}

// GetDictIteams mocks base method.
func (m *MockDataDictAccess) GetDictIteams(ctx context.Context, dictID string) (map[string][]map[string]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDictIteams", ctx, dictID)
	ret0, _ := ret[0].(map[string][]map[string]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDictIteams indicates an expected call of GetDictIteams.
func (mr *MockDataDictAccessMockRecorder) GetDictIteams(ctx, dictID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDictIteams", reflect.TypeOf((*MockDataDictAccess)(nil).GetDictIteams), ctx, dictID)
}
