// Code generated by MockGen. DO NOT EDIT.
// Source: ../interfaces/resource_access.go
//
// Generated by this command:
//
//	mockgen -source ../interfaces/resource_access.go -destination ../interfaces/mock/mock_resource_access.go
//

// Package mock_interfaces is a generated GoMock package.
package mock_interfaces

import (
	context "context"
	reflect "reflect"
	interfaces "vega-backend/interfaces"

	gomock "go.uber.org/mock/gomock"
)

// MockResourceAccess is a mock of ResourceAccess interface.
type MockResourceAccess struct {
	ctrl     *gomock.Controller
	recorder *MockResourceAccessMockRecorder
	isgomock struct{}
}

// MockResourceAccessMockRecorder is the mock recorder for MockResourceAccess.
type MockResourceAccessMockRecorder struct {
	mock *MockResourceAccess
}

// NewMockResourceAccess creates a new mock instance.
func NewMockResourceAccess(ctrl *gomock.Controller) *MockResourceAccess {
	mock := &MockResourceAccess{ctrl: ctrl}
	mock.recorder = &MockResourceAccessMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockResourceAccess) EXPECT() *MockResourceAccessMockRecorder {
	return m.recorder
}

// CheckExistByCategories mocks base method.
func (m *MockResourceAccess) CheckExistByCategories(ctx context.Context, catalogID string, categories []string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckExistByCategories", ctx, catalogID, categories)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckExistByCategories indicates an expected call of CheckExistByCategories.
func (mr *MockResourceAccessMockRecorder) CheckExistByCategories(ctx, catalogID, categories any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckExistByCategories", reflect.TypeOf((*MockResourceAccess)(nil).CheckExistByCategories), ctx, catalogID, categories)
}

// Create mocks base method.
func (m *MockResourceAccess) Create(ctx context.Context, resource *interfaces.Resource) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, resource)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockResourceAccessMockRecorder) Create(ctx, resource any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockResourceAccess)(nil).Create), ctx, resource)
}

// DeleteByCatalogIDs mocks base method.
func (m *MockResourceAccess) DeleteByCatalogIDs(ctx context.Context, catalogIDs []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByCatalogIDs", ctx, catalogIDs)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByCatalogIDs indicates an expected call of DeleteByCatalogIDs.
func (mr *MockResourceAccessMockRecorder) DeleteByCatalogIDs(ctx, catalogIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByCatalogIDs", reflect.TypeOf((*MockResourceAccess)(nil).DeleteByCatalogIDs), ctx, catalogIDs)
}

// DeleteByIDs mocks base method.
func (m *MockResourceAccess) DeleteByIDs(ctx context.Context, ids []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByIDs", ctx, ids)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByIDs indicates an expected call of DeleteByIDs.
func (mr *MockResourceAccessMockRecorder) DeleteByIDs(ctx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByIDs", reflect.TypeOf((*MockResourceAccess)(nil).DeleteByIDs), ctx, ids)
}

// GetByCatalogID mocks base method.
func (m *MockResourceAccess) GetByCatalogID(ctx context.Context, catalogID string) ([]*interfaces.Resource, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByCatalogID", ctx, catalogID)
	ret0, _ := ret[0].([]*interfaces.Resource)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByCatalogID indicates an expected call of GetByCatalogID.
func (mr *MockResourceAccessMockRecorder) GetByCatalogID(ctx, catalogID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByCatalogID", reflect.TypeOf((*MockResourceAccess)(nil).GetByCatalogID), ctx, catalogID)
}

// GetByID mocks base method.
func (m *MockResourceAccess) GetByID(ctx context.Context, id string) (*interfaces.Resource, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*interfaces.Resource)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockResourceAccessMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockResourceAccess)(nil).GetByID), ctx, id)
}

// GetByIDs mocks base method.
func (m *MockResourceAccess) GetByIDs(ctx context.Context, ids []string) ([]*interfaces.Resource, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByIDs", ctx, ids)
	ret0, _ := ret[0].([]*interfaces.Resource)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByIDs indicates an expected call of GetByIDs.
func (mr *MockResourceAccessMockRecorder) GetByIDs(ctx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByIDs", reflect.TypeOf((*MockResourceAccess)(nil).GetByIDs), ctx, ids)
}

// GetByName mocks base method.
func (m *MockResourceAccess) GetByName(ctx context.Context, catalogID, name string) (*interfaces.Resource, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByName", ctx, catalogID, name)
	ret0, _ := ret[0].(*interfaces.Resource)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByName indicates an expected call of GetByName.
func (mr *MockResourceAccessMockRecorder) GetByName(ctx, catalogID, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByName", reflect.TypeOf((*MockResourceAccess)(nil).GetByName), ctx, catalogID, name)
}

// List mocks base method.
func (m *MockResourceAccess) List(ctx context.Context, params interfaces.ResourcesQueryParams) ([]*interfaces.Resource, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, params)
	ret0, _ := ret[0].([]*interfaces.Resource)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockResourceAccessMockRecorder) List(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockResourceAccess)(nil).List), ctx, params)
}

// ListResourceSrcs mocks base method.
func (m *MockResourceAccess) ListResourceSrcs(ctx context.Context, params interfaces.ListResourcesQueryParams) ([]*interfaces.ListResourceEntry, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListResourceSrcs", ctx, params)
	ret0, _ := ret[0].([]*interfaces.ListResourceEntry)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListResourceSrcs indicates an expected call of ListResourceSrcs.
func (mr *MockResourceAccessMockRecorder) ListResourceSrcs(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListResourceSrcs", reflect.TypeOf((*MockResourceAccess)(nil).ListResourceSrcs), ctx, params)
}

// Update mocks base method.
func (m *MockResourceAccess) Update(ctx context.Context, resource *interfaces.Resource) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, resource)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockResourceAccessMockRecorder) Update(ctx, resource any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockResourceAccess)(nil).Update), ctx, resource)
}

// UpdateStatus mocks base method.
func (m *MockResourceAccess) UpdateStatus(ctx context.Context, id, status, statusMessage string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatus", ctx, id, status, statusMessage)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStatus indicates an expected call of UpdateStatus.
func (mr *MockResourceAccessMockRecorder) UpdateStatus(ctx, id, status, statusMessage any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatus", reflect.TypeOf((*MockResourceAccess)(nil).UpdateStatus), ctx, id, status, statusMessage)
}
